url=https://fx1qa.idsnext.live/#/login
username=kalingiri.nareshkumar@idsnext.com
password=Ids@2026

browser=chrome

# url=https://fx1staging.idsnext.live/
# username=prakash.dakshina@idsnext.com
# password=Ids@2026

