url=https://fx1qa.idsnext.live/#/login
username=dsingh.devstringx@hotmail.com
password=Ids@1001

browser=chrome

# url=https://fx1staging.idsnext.live/
# username=dsingh.devstringx@hotmail.com
# password=Ids@2026

